### ISSUE TITLE
Would it be possible to provide a sample vcap-local.json for CDE credentials? 

### ISSUE THREAD

**Issue by mwilcox12015** [IBM/dynamic-dashboard-demo#18]
RE: Ensure that vcap-local.json contains the CDE credentials
Would it be possible to provide a sample vcap-local.json for CDE credentials? 
We notice a vcap-local.sample file that contains a cloudant auth ?

**Comment by Shimueoka** [comment]
I think so too, vcap-local.sample is invaild
You can get VCAP_service.json when you push app source as a cloud foundry application.

I paste my vcap code below,  as a sample.
(vcap is masked , please change "XXXXXXXXX" to your credential )  

```
{
  "services": {
    "cloudantNoSQLDB": [
      {
        "credentials": {
          "url":"CLOUDANT_DATABASE_URL"
        },
        "label": "cloudantNoSQLDB"
      }
    ],
      "dynamic-dashboard-embedded": [
          {
              "label": "dynamic-dashboard-embedded",
              "provider": null,
              "plan": "lite",
              "name": "IBM Cognos Dashboard Embedded-XX",
              "tags": [
                  "business_analytics",
                  "ibm_created",
                  "rc_compatible",
                  "ibmcloud-alias"
              ],
              "instance_name": "IBM Cognos Dashboard Embedded-XX",
              "binding_name": null,
              "credentials": {
                "api_endpoint_url": "XXXXXXXXXXXXX",
                "apikey": "XXXXXXXXXXXXXXXX",
                "client_id": "XXXXXXXXXXXXXXXX",
                "client_secret": "XXXXXXXXXXXXXXXX",
                "iam_apikey_description": "XXXXXXXXXXXXXXXXXXXXXXXXX",
                "iam_apikey_name": "XXXXXXXX",
                "iam_role_crn": "XXXXXXXXXXXXXXXX",
                "iam_serviceid_crn": "XXXXXXXXXXXXXXXX"
              },
              "syslog_drain_url": null,
              "volume_mounts": []
          }
      ]
  }
}
```
I think sample app can work.

But It is ASIS

**Comment by martindohko** [comment]
Hola, sustituí las "XXXXXX" por mis datos de credencial pero cuando entro en http://localhost:3000 y le doy "Create a session" me aparece el siguiente warning y errores, después no me permite inicializar la API:

(node:9028) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.post failed!
Unhandled rejection TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'issuerCertificate' closes the circle
    at JSON.stringify (<anonymous>)
    at c:\CDE-master\server.js:80:24
    at tryCatcher (c:\CDE-master\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\CDE-master\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (c:\CDE-master\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (c:\CDE-master\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (c:\CDE-master\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (c:\CDE-master\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (c:\CDE-master\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\CDE-master\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate (internal/timers.js:456:21)

**Comment by playground** [comment]
@martindohko I got the same error when try to create a session.  Seems like https://ddetest-us-south.analytics.ibm.com/daas/v1/session is no longer valid.  I had to change to use https://dde-us-south.analytics.ibm.com/daas/v1/session instead.
